{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1691185f-8476-4c50-80e1-2a68fd80f145",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "np.random.seed(42)\n",
    "n = 800\n",
    "\n",
    "# Genotype distribution (Dutta 2024)\n",
    "genotypes = np.random.choice(['HbSS', 'HbSE', 'HbS-thal', 'HbSA'],\n",
    "                             size=n, p=[0.87, 0.06, 0.03, 0.04])\n",
    "\n",
    "# Age distribution (Dutta 2024)\n",
    "age_group_probs = [0.196, 0.50, 0.212, 0.092]\n",
    "age_ranges = [(0,10), (10,20), (20,30), (30,70)]\n",
    "ages = []\n",
    "for i, prob in enumerate(age_group_probs):\n",
    "    n_group = int(n * prob)\n",
    "    ages.extend(np.random.randint(age_ranges[i][0], age_ranges[i][1], n_group).tolist())\n",
    "\n",
    "while len(ages) < n:\n",
    "    ages.append(int(np.random.randint(10, 20)))\n",
    "ages = ages[:n]  # ensure exactly 800\n",
    "ages = np.array(ages, dtype=object)\n",
    "\n",
    "# Gender (Dutta 2024)\n",
    "genders = np.random.choice(['M', 'F'], size=n, p=[0.544, 0.456])\n",
    "\n",
    "# Districts – Odisha and Assam\n",
    "odisha_dists = ['Sundargarh', 'Koraput', 'Mayurbhanj', 'Kalahandi', 'Nabarangpur']\n",
    "assam_dists = ['Dibrugarh', 'Tinsukia', 'Sivasagar', 'Jorhat', 'Golaghat']\n",
    "all_dists = odisha_dists + assam_dists\n",
    "dist_probs = [0.12,0.10,0.08,0.07,0.06] + [0.20,0.15,0.10,0.07,0.05]\n",
    "districts = np.random.choice(all_dists, size=n, p=dist_probs)\n",
    "\n",
    "# Lab values (from Mishra 2025)\n",
    "def assign_lab(genotype):\n",
    "    if genotype == 'HbSS':\n",
    "        hb = np.random.normal(8.32, 0.21)\n",
    "        hbs = np.random.normal(86.4, 1.0)\n",
    "    elif genotype == 'HbSA':\n",
    "        hb = np.random.normal(11.27, 0.18)\n",
    "        hbs = np.random.normal(40.31, 0.71)\n",
    "    else:   # HbSE, HbS-thal – approximate\n",
    "        hb = np.random.normal(10.0, 1.5)\n",
    "        hbs = np.random.normal(50, 5)\n",
    "    return round(hb,1), round(hbs,1)\n",
    "\n",
    "hb_vals = []\n",
    "hbs_vals = []\n",
    "for g in genotypes:\n",
    "    hb, hbs = assign_lab(g)\n",
    "    hb_vals.append(hb)\n",
    "    hbs_vals.append(hbs)\n",
    "\n",
    "# Symptoms (Dutta 2024)\n",
    "def symptoms(genotype):\n",
    "    if genotype == 'HbSS':\n",
    "        fever = np.random.choice(['Yes','No'], p=[0.612,0.388])\n",
    "        bone_pain = np.random.choice(['Yes','No'], p=[0.484,0.516])\n",
    "    else:\n",
    "        fever = np.random.choice(['Yes','No'], p=[0.2,0.8])\n",
    "        bone_pain = np.random.choice(['Yes','No'], p=[0.15,0.85])\n",
    "    return fever, bone_pain\n",
    "\n",
    "fever_vals = []\n",
    "bone_pain_vals = []\n",
    "for g in genotypes:\n",
    "    f, bp = symptoms(g)\n",
    "    fever_vals.append(f)\n",
    "    bone_pain_vals.append(bp)\n",
    "\n",
    "# Awareness (Mishra 2025)\n",
    "awareness = []\n",
    "for _ in range(n):\n",
    "    r = np.random.random()\n",
    "    if r < 0.543:\n",
    "        awareness.append('Never heard')\n",
    "    else:\n",
    "        r2 = np.random.random()\n",
    "        if r2 < (0.0937 / 0.457):\n",
    "            awareness.append('Knows inherited')\n",
    "        else:\n",
    "            awareness.append(\"Heard but don't know inherited\")\n",
    "\n",
    "# black magic belief - 44.55% among those who heard (mishra)\n",
    "black_magic = []\n",
    "for a in awareness:\n",
    "    if a == 'Never heard':\n",
    "        black_magic.append('No')\n",
    "    else:\n",
    "        black_magic.append(np.random.choice(['Yes','No'], p=[0.4455,0.5545]))\n",
    "\n",
    "# Screening & treatment\n",
    "screened = []\n",
    "for g in genotypes:\n",
    "    if g == 'HbSS':\n",
    "        screened.append(np.random.choice(['Yes','No'], p=[0.5,0.5]))\n",
    "    else:\n",
    "        # From Bindhani: only 8.89% of carriers had been screened before study\n",
    "        screened.append(np.random.choice(['Yes','No'], p=[0.0889,0.9111]))\n",
    "\n",
    "hydroxyurea = []\n",
    "transfusions = []\n",
    "for g in genotypes:\n",
    "    if g == 'HbSS':\n",
    "        hu = np.random.choice(['Yes','No'], p=[0.5,0.5])\n",
    "        trans = np.random.choice(['0-4/yr','5-8/yr','9-12/yr','>12/yr'],\n",
    "                                 p=[0.28,0.40,0.32,0.0])  # from Dutta\n",
    "    else:\n",
    "        hu = 'No'\n",
    "        trans = 'Rarely'\n",
    "    hydroxyurea.append(hu)\n",
    "    transfusions.append(trans)\n",
    "\n",
    "# Lost to follow-up \n",
    "ltfu = np.random.choice(['Active','Lost to follow-up'], size=n, p=[0.85,0.15])\n",
    "#check length\n",
    "for name, arr in [\n",
    "    ('genotypes', genotypes), ('ages', ages), ('genders', genders),\n",
    "    ('districts', districts), ('hb_vals', hb_vals), ('hbs_vals', hbs_vals),\n",
    "    ('fever_vals', fever_vals), ('bone_pain_vals', bone_pain_vals),\n",
    "    ('awareness', awareness), ('black_magic', black_magic),\n",
    "    ('screened', screened), ('hydroxyurea', hydroxyurea),\n",
    "    ('transfusions', transfusions), ('ltfu', ltfu)\n",
    "]:\n",
    "    print(f\"{name}: {len(arr)}\")\n",
    "    \n",
    "df = pd.DataFrame({\n",
    "    'patient_id': [f'SCD{i:04d}' for i in range(1,n+1)],\n",
    "    'age': ages,\n",
    "    'gender': genders,\n",
    "    'district': districts,\n",
    "    'genotype': genotypes,\n",
    "    'hb_g_dl': hb_vals,\n",
    "    'hbs_percent': hbs_vals,\n",
    "    'fever': fever_vals,\n",
    "    'bone_pain': bone_pain_vals,\n",
    "    'awareness': awareness,\n",
    "    'belief_black_magic': black_magic,\n",
    "    'screened': screened,\n",
    "    'hydroxyurea': hydroxyurea,\n",
    "    'transfusions_per_year': transfusions,\n",
    "    'follow_up_status': ltfu\n",
    "})\n",
    "\n",
    "# Save to CSV\n",
    "output_file = 'scd_screening_data.csv'\n",
    "df.to_csv(output_file, index=False)\n",
    "print(f\"Data saved to {output_file} in {os.getcwd()}\")\n",
    "print(f\"Shape: {df.shape}\")\n",
    "print(\"First 5 rows:\")\n",
    "print(df.head())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ffe3b497-fa4c-4075-8f42-5c40f0d16324",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
